source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

link_with 'Catty'

target 'Catty' do

pod 'MXSegmentedPager', :git => 'https://github.com/maxep/MXSegmentedPager.git'
pod 'M13ProgressSuite', '~> 1.2.7'
pod 'Bohr'
pod 'Shimmer'
pod 'MYBlurIntroductionView'
pod 'TTTAttributedLabel'
pod 'Siren'
pod 'QRCodeReader.swift', '~> 5.3.1'
pod 'SDCAlertView', '~> 4.0'
pod 'Alamofire', '~> 3.1.4'

end
